<?php 
return [
'cnf_appname' 			=> 'PARKUR',
'cnf_appdesc' 			=> 'Build and Development',
'cnf_comname' 			=> 'PARKUR',
'cnf_email' 			=> 'superadmin@mail.com',
'cnf_metakey' 			=> 'PARKUR',
'cnf_metadesc' 		=> 'PARKUR',
'cnf_group' 			=> '24',
'cnf_activation' 		=> 'manual',
'cnf_multilang' 		=> '0',
'cnf_lang' 			=> 'en',
'cnf_regist' 			=> 'false',
'cnf_front' 			=> 'false',
'cnf_recaptcha' 		=> 'false',
'cnf_theme' 			=> 'default',
'cnf_backend' 			=> 'minimal',
'cnf_recaptchapublickey' => '6Le2bjQUAAAAABascn2t0WsRjZbmL6EnxFJUU1H_',
'cnf_recaptchaprivatekey' => '6Le2bjQUAAAAAI6ZKqgzoYS21umpeper74sMK38s',
'cnf_mode' 			=> 'production',
'cnf_logo' 			=> 'backend-logo.jpg',
'cnf_allowip' 			=> '',
'cnf_restrictip' 		=> '192.116.134 , 194.111.606.21',
'cnf_mail' 			=> 'swift',
'cnf_maps' 			=> 'AIzaSyDBkmSn9WCCGMYN2LWoD4Y7Qz2i7rwlm3s',
'cnf_date' 			=> 'Y-m-d',
];
